name: Security Scan and Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trufflehog_scan:
    name: Scan for Credentials
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run TruffleHog Scan
        run: |
          docker run --rm -v $(pwd):/src trufflesecurity/trufflehog:latest \
            git --path /src --json | tee trufflehog_results.json

  snyk_sca:
    name: SCA with Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Snyk CLI
        run: |
          curl -Lo snyk https://github.com/snyk/snyk/releases/latest/download/snyk-linux
          chmod +x snyk
          sudo mv snyk /usr/local/bin/

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run SCA Analysis
        run: snyk test --json | tee snyk_sca_results.json

  snyk_sast:
    name: SAST with Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run SAST Analysis
        run: snyk code test --json | tee snyk_sast_results.json

  docker_build_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [trufflehog_scan, snyk_sca, snyk_sast]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_REPO }}:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_REPO }}:latest
