name: Security Scan and Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan_and_docker:
    name: Security Scan & Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run TruffleHog Scan
        run: |
          docker run --rm -v $(pwd):/src trufflesecurity/trufflehog:latest \
            filesystem /src --json | tee trufflehog_results.json

      - name: Install Snyk CLI
        run: |
          curl -Lo snyk https://github.com/snyk/snyk/releases/latest/download/snyk-linux
          chmod +x snyk
          sudo mv snyk /usr/local/bin/

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip3 install -r requirements.txt
          else
            echo "No requirements.txt found, skipping."
          fi

      - name: Run SCA Analysis
        run: snyk test --json | tee snyk_sca_results.json

      - name: Run SAST Analysis
        run: snyk code test --json | tee snyk_sast_results.json

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_REPO }}:latest .
          docker push ${{ secrets.DOCKER_REPO }}:latest
